name: Deploy from main

on:
  workflow_run:
    workflows: ["Build Dev"]
    types: ["completed"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup SSH
        run:

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Deploy
        run:
